[build]
target = "aarch64-apple-darwin"

[unstable]
build-std = ["std", "core", "alloc", "panic_abort"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "panic=abort", "-C", "link-args=-lSystem -Wl,-e,_main"]

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
rustflags = [
    "-C",
    "panic=abort",
    "-C",
    "opt-level=z",
    "-C",
    "codegen-units=1",
]
